# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='show_num',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
