# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0003_auto_20171019_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='title',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
